# Generated by Django 4.0.5 on 2022-07-10 15:24

from django.db import migrations, models
import users.models
import users.storage


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=255)),
                ('ProblemID', models.IntegerField(max_length=255)),
                ('Language', models.CharField(choices=[('', 'Choose...'), ('Py', 'Python'), ('C++', 'C++'), ('Java', 'JavaLang'), ('SQL', 'Standard Query Language'), ('PHP', 'PHP'), ('R', 'R'), ('Perl', 'Perl'), ('C#', 'C#'), ('js', 'JavaScript')], max_length=255)),
                ('File', models.FileField(storage=users.storage.OverwriteStorage(), upload_to=users.models.user_directory_path)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(storage=users.storage.OverwriteStorage(), upload_to='documents/'),
        ),
    ]
